version: "3.3"

services:
  dp-static-file-publisher:
    image: template_test
    expose:
      - "24900"
    ports:
      - 24900:24900
    volumes:
      - /Users/dionisilola/src/github.com/ONSdigital/dp-s3:/Users/dionisilola/src/github.com/ONSdigital/dp-s3
    env_file:
      - docker.env
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-sSf", "http://localhost:24900/health" ]
      interval: 30s
      timeout: 10s
      retries: 10
