version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --list  --bootstrap-server kafka:9092" ]
      interval: 90s
      timeout: 90s
      retries: 3

  vault:
    image: hashicorp/vault:latest
    restart: always
    ports:
      - "8200:8200/tcp"
    entrypoint: vault server -dev -dev-kv-v1 -dev-root-token-id="0000-0000-0000-0000"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: '0000-0000-0000-0000'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'

  localstack:
    image: localstack/localstack
    ports:
      - '4566-4583'
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - "${TMPDIR:-/tmp}/localstack:/var/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
