// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-static-file-publisher/file"
	"sync"
)

// Ensure, that FilesServiceMock does implement file.FilesService.
// If this is not the case, regenerate this file with moq.
var _ file.FilesService = &FilesServiceMock{}

// FilesServiceMock is a mock implementation of file.FilesService.
//
// 	func TestSomethingThatUsesFilesService(t *testing.T) {
//
// 		// make and configure a mocked file.FilesService
// 		mockedFilesService := &FilesServiceMock{
// 			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 				panic("mock out the Checker method")
// 			},
// 			MarkFileDecryptedFunc: func(ctx context.Context, path string, etag string) error {
// 				panic("mock out the MarkFileDecrypted method")
// 			},
// 		}
//
// 		// use mockedFilesService in code that requires file.FilesService
// 		// and then make assertions.
//
// 	}
type FilesServiceMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// MarkFileDecryptedFunc mocks the MarkFileDecrypted method.
	MarkFileDecryptedFunc func(ctx context.Context, path string, etag string) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// MarkFileDecrypted holds details about calls to the MarkFileDecrypted method.
		MarkFileDecrypted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Etag is the etag argument value.
			Etag string
		}
	}
	lockChecker           sync.RWMutex
	lockMarkFileDecrypted sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *FilesServiceMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("FilesServiceMock.CheckerFunc: method is nil but FilesService.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedFilesService.CheckerCalls())
func (mock *FilesServiceMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// MarkFileDecrypted calls MarkFileDecryptedFunc.
func (mock *FilesServiceMock) MarkFileDecrypted(ctx context.Context, path string, etag string) error {
	if mock.MarkFileDecryptedFunc == nil {
		panic("FilesServiceMock.MarkFileDecryptedFunc: method is nil but FilesService.MarkFileDecrypted was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Etag string
	}{
		Ctx:  ctx,
		Path: path,
		Etag: etag,
	}
	mock.lockMarkFileDecrypted.Lock()
	mock.calls.MarkFileDecrypted = append(mock.calls.MarkFileDecrypted, callInfo)
	mock.lockMarkFileDecrypted.Unlock()
	return mock.MarkFileDecryptedFunc(ctx, path, etag)
}

// MarkFileDecryptedCalls gets all the calls that were made to MarkFileDecrypted.
// Check the length with:
//     len(mockedFilesService.MarkFileDecryptedCalls())
func (mock *FilesServiceMock) MarkFileDecryptedCalls() []struct {
	Ctx  context.Context
	Path string
	Etag string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Etag string
	}
	mock.lockMarkFileDecrypted.RLock()
	calls = mock.calls.MarkFileDecrypted
	mock.lockMarkFileDecrypted.RUnlock()
	return calls
}
