// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-static-file-publisher/file"
	"github.com/aws/aws-sdk-go/service/s3/s3manager"
	"io"
	"sync"
)

// Ensure, that S3ClientV2Mock does implement file.S3ClientV2.
// If this is not the case, regenerate this file with moq.
var _ file.S3ClientV2 = &S3ClientV2Mock{}

// S3ClientV2Mock is a mock implementation of file.S3ClientV2.
//
// 	func TestSomethingThatUsesS3ClientV2(t *testing.T) {
//
// 		// make and configure a mocked file.S3ClientV2
// 		mockedS3ClientV2 := &S3ClientV2Mock{
// 			GetWithPSKFunc: func(key string, psk []byte) (io.ReadCloser, *int64, error) {
// 				panic("mock out the GetWithPSK method")
// 			},
// 			UploadFunc: func(input *s3manager.UploadInput, options ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error) {
// 				panic("mock out the Upload method")
// 			},
// 		}
//
// 		// use mockedS3ClientV2 in code that requires file.S3ClientV2
// 		// and then make assertions.
//
// 	}
type S3ClientV2Mock struct {
	// GetWithPSKFunc mocks the GetWithPSK method.
	GetWithPSKFunc func(key string, psk []byte) (io.ReadCloser, *int64, error)

	// UploadFunc mocks the Upload method.
	UploadFunc func(input *s3manager.UploadInput, options ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetWithPSK holds details about calls to the GetWithPSK method.
		GetWithPSK []struct {
			// Key is the key argument value.
			Key string
			// Psk is the psk argument value.
			Psk []byte
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// Input is the input argument value.
			Input *s3manager.UploadInput
			// Options is the options argument value.
			Options []func(*s3manager.Uploader)
		}
	}
	lockGetWithPSK sync.RWMutex
	lockUpload     sync.RWMutex
}

// GetWithPSK calls GetWithPSKFunc.
func (mock *S3ClientV2Mock) GetWithPSK(key string, psk []byte) (io.ReadCloser, *int64, error) {
	if mock.GetWithPSKFunc == nil {
		panic("S3ClientV2Mock.GetWithPSKFunc: method is nil but S3ClientV2.GetWithPSK was just called")
	}
	callInfo := struct {
		Key string
		Psk []byte
	}{
		Key: key,
		Psk: psk,
	}
	mock.lockGetWithPSK.Lock()
	mock.calls.GetWithPSK = append(mock.calls.GetWithPSK, callInfo)
	mock.lockGetWithPSK.Unlock()
	return mock.GetWithPSKFunc(key, psk)
}

// GetWithPSKCalls gets all the calls that were made to GetWithPSK.
// Check the length with:
//     len(mockedS3ClientV2.GetWithPSKCalls())
func (mock *S3ClientV2Mock) GetWithPSKCalls() []struct {
	Key string
	Psk []byte
} {
	var calls []struct {
		Key string
		Psk []byte
	}
	mock.lockGetWithPSK.RLock()
	calls = mock.calls.GetWithPSK
	mock.lockGetWithPSK.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *S3ClientV2Mock) Upload(input *s3manager.UploadInput, options ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error) {
	if mock.UploadFunc == nil {
		panic("S3ClientV2Mock.UploadFunc: method is nil but S3ClientV2.Upload was just called")
	}
	callInfo := struct {
		Input   *s3manager.UploadInput
		Options []func(*s3manager.Uploader)
	}{
		Input:   input,
		Options: options,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(input, options...)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//     len(mockedS3ClientV2.UploadCalls())
func (mock *S3ClientV2Mock) UploadCalls() []struct {
	Input   *s3manager.UploadInput
	Options []func(*s3manager.Uploader)
} {
	var calls []struct {
		Input   *s3manager.UploadInput
		Options []func(*s3manager.Uploader)
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}
