// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-static-file-publisher/service"
	"sync"
)

var (
	lockImageAPIClientMockChecker sync.RWMutex
)

// Ensure, that ImageAPIClientMock does implement service.ImageAPIClient.
// If this is not the case, regenerate this file with moq.
var _ service.ImageAPIClient = &ImageAPIClientMock{}

// ImageAPIClientMock is a mock implementation of service.ImageAPIClient.
//
//     func TestSomethingThatUsesImageAPIClient(t *testing.T) {
//
//         // make and configure a mocked service.ImageAPIClient
//         mockedImageAPIClient := &ImageAPIClientMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//         }
//
//         // use mockedImageAPIClient in code that requires service.ImageAPIClient
//         // and then make assertions.
//
//     }
type ImageAPIClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
	}
}

// Checker calls CheckerFunc.
func (mock *ImageAPIClientMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ImageAPIClientMock.CheckerFunc: method is nil but ImageAPIClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockImageAPIClientMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockImageAPIClientMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedImageAPIClient.CheckerCalls())
func (mock *ImageAPIClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockImageAPIClientMockChecker.RLock()
	calls = mock.calls.Checker
	lockImageAPIClientMockChecker.RUnlock()
	return calls
}
