// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	kafka "github.com/ONSdigital/dp-kafka/v4"
	"github.com/ONSdigital/dp-static-file-publisher/config"
	"github.com/ONSdigital/dp-static-file-publisher/event"
	"github.com/ONSdigital/dp-static-file-publisher/file"
	"github.com/ONSdigital/dp-static-file-publisher/service"
	"github.com/aws/aws-sdk-go-v2/aws"
	"net/http"
	"sync"
)

// Ensure, that InitialiserMock does implement service.Initialiser.
// If this is not the case, regenerate this file with moq.
var _ service.Initialiser = &InitialiserMock{}

// InitialiserMock is a mock implementation of service.Initialiser.
//
//	func TestSomethingThatUsesInitialiser(t *testing.T) {
//
//		// make and configure a mocked service.Initialiser
//		mockedInitialiser := &InitialiserMock{
//			DoGetFilesServiceFunc: func(ctx context.Context, cfg *config.Config) file.FilesService {
//				panic("mock out the DoGetFilesService method")
//			},
//			DoGetHTTPServerFunc: func(bindAddr string, router http.Handler) service.HTTPServer {
//				panic("mock out the DoGetHTTPServer method")
//			},
//			DoGetHealthCheckFunc: func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
//				panic("mock out the DoGetHealthCheck method")
//			},
//			DoGetImageAPIClientFunc: func(ctx context.Context, cfg *config.Config) event.ImageAPIClient {
//				panic("mock out the DoGetImageAPIClient method")
//			},
//			DoGetKafkaFilePublishedConsumerFunc: func(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error) {
//				panic("mock out the DoGetKafkaFilePublishedConsumer method")
//			},
//			DoGetKafkaImagePublishedConsumerFunc: func(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error) {
//				panic("mock out the DoGetKafkaImagePublishedConsumer method")
//			},
//			DoGetS3ClientFunc: func(ctx context.Context, awsRegion string, bucketName string) (file.S3Client, error) {
//				panic("mock out the DoGetS3Client method")
//			},
//			DoGetS3ClientWithConfigFunc: func(bucketName string, cfg aws.Config) (file.S3Client, error) {
//				panic("mock out the DoGetS3ClientWithConfig method")
//			},
//		}
//
//		// use mockedInitialiser in code that requires service.Initialiser
//		// and then make assertions.
//
//	}
type InitialiserMock struct {
	// DoGetFilesServiceFunc mocks the DoGetFilesService method.
	DoGetFilesServiceFunc func(ctx context.Context, cfg *config.Config) file.FilesService

	// DoGetHTTPServerFunc mocks the DoGetHTTPServer method.
	DoGetHTTPServerFunc func(bindAddr string, router http.Handler) service.HTTPServer

	// DoGetHealthCheckFunc mocks the DoGetHealthCheck method.
	DoGetHealthCheckFunc func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error)

	// DoGetImageAPIClientFunc mocks the DoGetImageAPIClient method.
	DoGetImageAPIClientFunc func(ctx context.Context, cfg *config.Config) event.ImageAPIClient

	// DoGetKafkaFilePublishedConsumerFunc mocks the DoGetKafkaFilePublishedConsumer method.
	DoGetKafkaFilePublishedConsumerFunc func(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error)

	// DoGetKafkaImagePublishedConsumerFunc mocks the DoGetKafkaImagePublishedConsumer method.
	DoGetKafkaImagePublishedConsumerFunc func(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error)

	// DoGetS3ClientFunc mocks the DoGetS3Client method.
	DoGetS3ClientFunc func(ctx context.Context, awsRegion string, bucketName string) (file.S3Client, error)

	// DoGetS3ClientWithConfigFunc mocks the DoGetS3ClientWithConfig method.
	DoGetS3ClientWithConfigFunc func(bucketName string, cfg aws.Config) (file.S3Client, error)

	// calls tracks calls to the methods.
	calls struct {
		// DoGetFilesService holds details about calls to the DoGetFilesService method.
		DoGetFilesService []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
		}
		// DoGetHTTPServer holds details about calls to the DoGetHTTPServer method.
		DoGetHTTPServer []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Router is the router argument value.
			Router http.Handler
		}
		// DoGetHealthCheck holds details about calls to the DoGetHealthCheck method.
		DoGetHealthCheck []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// BuildTime is the buildTime argument value.
			BuildTime string
			// GitCommit is the gitCommit argument value.
			GitCommit string
			// Version is the version argument value.
			Version string
		}
		// DoGetImageAPIClient holds details about calls to the DoGetImageAPIClient method.
		DoGetImageAPIClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
		}
		// DoGetKafkaFilePublishedConsumer holds details about calls to the DoGetKafkaFilePublishedConsumer method.
		DoGetKafkaFilePublishedConsumer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
		}
		// DoGetKafkaImagePublishedConsumer holds details about calls to the DoGetKafkaImagePublishedConsumer method.
		DoGetKafkaImagePublishedConsumer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg *config.Config
		}
		// DoGetS3Client holds details about calls to the DoGetS3Client method.
		DoGetS3Client []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AwsRegion is the awsRegion argument value.
			AwsRegion string
			// BucketName is the bucketName argument value.
			BucketName string
		}
		// DoGetS3ClientWithConfig holds details about calls to the DoGetS3ClientWithConfig method.
		DoGetS3ClientWithConfig []struct {
			// BucketName is the bucketName argument value.
			BucketName string
			// Cfg is the cfg argument value.
			Cfg aws.Config
		}
	}
	lockDoGetFilesService                sync.RWMutex
	lockDoGetHTTPServer                  sync.RWMutex
	lockDoGetHealthCheck                 sync.RWMutex
	lockDoGetImageAPIClient              sync.RWMutex
	lockDoGetKafkaFilePublishedConsumer  sync.RWMutex
	lockDoGetKafkaImagePublishedConsumer sync.RWMutex
	lockDoGetS3Client                    sync.RWMutex
	lockDoGetS3ClientWithConfig          sync.RWMutex
}

// DoGetFilesService calls DoGetFilesServiceFunc.
func (mock *InitialiserMock) DoGetFilesService(ctx context.Context, cfg *config.Config) file.FilesService {
	if mock.DoGetFilesServiceFunc == nil {
		panic("InitialiserMock.DoGetFilesServiceFunc: method is nil but Initialiser.DoGetFilesService was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg *config.Config
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockDoGetFilesService.Lock()
	mock.calls.DoGetFilesService = append(mock.calls.DoGetFilesService, callInfo)
	mock.lockDoGetFilesService.Unlock()
	return mock.DoGetFilesServiceFunc(ctx, cfg)
}

// DoGetFilesServiceCalls gets all the calls that were made to DoGetFilesService.
// Check the length with:
//
//	len(mockedInitialiser.DoGetFilesServiceCalls())
func (mock *InitialiserMock) DoGetFilesServiceCalls() []struct {
	Ctx context.Context
	Cfg *config.Config
} {
	var calls []struct {
		Ctx context.Context
		Cfg *config.Config
	}
	mock.lockDoGetFilesService.RLock()
	calls = mock.calls.DoGetFilesService
	mock.lockDoGetFilesService.RUnlock()
	return calls
}

// DoGetHTTPServer calls DoGetHTTPServerFunc.
func (mock *InitialiserMock) DoGetHTTPServer(bindAddr string, router http.Handler) service.HTTPServer {
	if mock.DoGetHTTPServerFunc == nil {
		panic("InitialiserMock.DoGetHTTPServerFunc: method is nil but Initialiser.DoGetHTTPServer was just called")
	}
	callInfo := struct {
		BindAddr string
		Router   http.Handler
	}{
		BindAddr: bindAddr,
		Router:   router,
	}
	mock.lockDoGetHTTPServer.Lock()
	mock.calls.DoGetHTTPServer = append(mock.calls.DoGetHTTPServer, callInfo)
	mock.lockDoGetHTTPServer.Unlock()
	return mock.DoGetHTTPServerFunc(bindAddr, router)
}

// DoGetHTTPServerCalls gets all the calls that were made to DoGetHTTPServer.
// Check the length with:
//
//	len(mockedInitialiser.DoGetHTTPServerCalls())
func (mock *InitialiserMock) DoGetHTTPServerCalls() []struct {
	BindAddr string
	Router   http.Handler
} {
	var calls []struct {
		BindAddr string
		Router   http.Handler
	}
	mock.lockDoGetHTTPServer.RLock()
	calls = mock.calls.DoGetHTTPServer
	mock.lockDoGetHTTPServer.RUnlock()
	return calls
}

// DoGetHealthCheck calls DoGetHealthCheckFunc.
func (mock *InitialiserMock) DoGetHealthCheck(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
	if mock.DoGetHealthCheckFunc == nil {
		panic("InitialiserMock.DoGetHealthCheckFunc: method is nil but Initialiser.DoGetHealthCheck was just called")
	}
	callInfo := struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}{
		Cfg:       cfg,
		BuildTime: buildTime,
		GitCommit: gitCommit,
		Version:   version,
	}
	mock.lockDoGetHealthCheck.Lock()
	mock.calls.DoGetHealthCheck = append(mock.calls.DoGetHealthCheck, callInfo)
	mock.lockDoGetHealthCheck.Unlock()
	return mock.DoGetHealthCheckFunc(cfg, buildTime, gitCommit, version)
}

// DoGetHealthCheckCalls gets all the calls that were made to DoGetHealthCheck.
// Check the length with:
//
//	len(mockedInitialiser.DoGetHealthCheckCalls())
func (mock *InitialiserMock) DoGetHealthCheckCalls() []struct {
	Cfg       *config.Config
	BuildTime string
	GitCommit string
	Version   string
} {
	var calls []struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}
	mock.lockDoGetHealthCheck.RLock()
	calls = mock.calls.DoGetHealthCheck
	mock.lockDoGetHealthCheck.RUnlock()
	return calls
}

// DoGetImageAPIClient calls DoGetImageAPIClientFunc.
func (mock *InitialiserMock) DoGetImageAPIClient(ctx context.Context, cfg *config.Config) event.ImageAPIClient {
	if mock.DoGetImageAPIClientFunc == nil {
		panic("InitialiserMock.DoGetImageAPIClientFunc: method is nil but Initialiser.DoGetImageAPIClient was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg *config.Config
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockDoGetImageAPIClient.Lock()
	mock.calls.DoGetImageAPIClient = append(mock.calls.DoGetImageAPIClient, callInfo)
	mock.lockDoGetImageAPIClient.Unlock()
	return mock.DoGetImageAPIClientFunc(ctx, cfg)
}

// DoGetImageAPIClientCalls gets all the calls that were made to DoGetImageAPIClient.
// Check the length with:
//
//	len(mockedInitialiser.DoGetImageAPIClientCalls())
func (mock *InitialiserMock) DoGetImageAPIClientCalls() []struct {
	Ctx context.Context
	Cfg *config.Config
} {
	var calls []struct {
		Ctx context.Context
		Cfg *config.Config
	}
	mock.lockDoGetImageAPIClient.RLock()
	calls = mock.calls.DoGetImageAPIClient
	mock.lockDoGetImageAPIClient.RUnlock()
	return calls
}

// DoGetKafkaFilePublishedConsumer calls DoGetKafkaFilePublishedConsumerFunc.
func (mock *InitialiserMock) DoGetKafkaFilePublishedConsumer(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error) {
	if mock.DoGetKafkaFilePublishedConsumerFunc == nil {
		panic("InitialiserMock.DoGetKafkaFilePublishedConsumerFunc: method is nil but Initialiser.DoGetKafkaFilePublishedConsumer was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg *config.Config
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockDoGetKafkaFilePublishedConsumer.Lock()
	mock.calls.DoGetKafkaFilePublishedConsumer = append(mock.calls.DoGetKafkaFilePublishedConsumer, callInfo)
	mock.lockDoGetKafkaFilePublishedConsumer.Unlock()
	return mock.DoGetKafkaFilePublishedConsumerFunc(ctx, cfg)
}

// DoGetKafkaFilePublishedConsumerCalls gets all the calls that were made to DoGetKafkaFilePublishedConsumer.
// Check the length with:
//
//	len(mockedInitialiser.DoGetKafkaFilePublishedConsumerCalls())
func (mock *InitialiserMock) DoGetKafkaFilePublishedConsumerCalls() []struct {
	Ctx context.Context
	Cfg *config.Config
} {
	var calls []struct {
		Ctx context.Context
		Cfg *config.Config
	}
	mock.lockDoGetKafkaFilePublishedConsumer.RLock()
	calls = mock.calls.DoGetKafkaFilePublishedConsumer
	mock.lockDoGetKafkaFilePublishedConsumer.RUnlock()
	return calls
}

// DoGetKafkaImagePublishedConsumer calls DoGetKafkaImagePublishedConsumerFunc.
func (mock *InitialiserMock) DoGetKafkaImagePublishedConsumer(ctx context.Context, cfg *config.Config) (kafka.IConsumerGroup, error) {
	if mock.DoGetKafkaImagePublishedConsumerFunc == nil {
		panic("InitialiserMock.DoGetKafkaImagePublishedConsumerFunc: method is nil but Initialiser.DoGetKafkaImagePublishedConsumer was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg *config.Config
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockDoGetKafkaImagePublishedConsumer.Lock()
	mock.calls.DoGetKafkaImagePublishedConsumer = append(mock.calls.DoGetKafkaImagePublishedConsumer, callInfo)
	mock.lockDoGetKafkaImagePublishedConsumer.Unlock()
	return mock.DoGetKafkaImagePublishedConsumerFunc(ctx, cfg)
}

// DoGetKafkaImagePublishedConsumerCalls gets all the calls that were made to DoGetKafkaImagePublishedConsumer.
// Check the length with:
//
//	len(mockedInitialiser.DoGetKafkaImagePublishedConsumerCalls())
func (mock *InitialiserMock) DoGetKafkaImagePublishedConsumerCalls() []struct {
	Ctx context.Context
	Cfg *config.Config
} {
	var calls []struct {
		Ctx context.Context
		Cfg *config.Config
	}
	mock.lockDoGetKafkaImagePublishedConsumer.RLock()
	calls = mock.calls.DoGetKafkaImagePublishedConsumer
	mock.lockDoGetKafkaImagePublishedConsumer.RUnlock()
	return calls
}

// DoGetS3Client calls DoGetS3ClientFunc.
func (mock *InitialiserMock) DoGetS3Client(ctx context.Context, awsRegion string, bucketName string) (file.S3Client, error) {
	if mock.DoGetS3ClientFunc == nil {
		panic("InitialiserMock.DoGetS3ClientFunc: method is nil but Initialiser.DoGetS3Client was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		AwsRegion  string
		BucketName string
	}{
		Ctx:        ctx,
		AwsRegion:  awsRegion,
		BucketName: bucketName,
	}
	mock.lockDoGetS3Client.Lock()
	mock.calls.DoGetS3Client = append(mock.calls.DoGetS3Client, callInfo)
	mock.lockDoGetS3Client.Unlock()
	return mock.DoGetS3ClientFunc(ctx, awsRegion, bucketName)
}

// DoGetS3ClientCalls gets all the calls that were made to DoGetS3Client.
// Check the length with:
//
//	len(mockedInitialiser.DoGetS3ClientCalls())
func (mock *InitialiserMock) DoGetS3ClientCalls() []struct {
	Ctx        context.Context
	AwsRegion  string
	BucketName string
} {
	var calls []struct {
		Ctx        context.Context
		AwsRegion  string
		BucketName string
	}
	mock.lockDoGetS3Client.RLock()
	calls = mock.calls.DoGetS3Client
	mock.lockDoGetS3Client.RUnlock()
	return calls
}

// DoGetS3ClientWithConfig calls DoGetS3ClientWithConfigFunc.
func (mock *InitialiserMock) DoGetS3ClientWithConfig(bucketName string, cfg aws.Config) (file.S3Client, error) {
	if mock.DoGetS3ClientWithConfigFunc == nil {
		panic("InitialiserMock.DoGetS3ClientWithConfigFunc: method is nil but Initialiser.DoGetS3ClientWithConfig was just called")
	}
	callInfo := struct {
		BucketName string
		Cfg        aws.Config
	}{
		BucketName: bucketName,
		Cfg:        cfg,
	}
	mock.lockDoGetS3ClientWithConfig.Lock()
	mock.calls.DoGetS3ClientWithConfig = append(mock.calls.DoGetS3ClientWithConfig, callInfo)
	mock.lockDoGetS3ClientWithConfig.Unlock()
	return mock.DoGetS3ClientWithConfigFunc(bucketName, cfg)
}

// DoGetS3ClientWithConfigCalls gets all the calls that were made to DoGetS3ClientWithConfig.
// Check the length with:
//
//	len(mockedInitialiser.DoGetS3ClientWithConfigCalls())
func (mock *InitialiserMock) DoGetS3ClientWithConfigCalls() []struct {
	BucketName string
	Cfg        aws.Config
} {
	var calls []struct {
		BucketName string
		Cfg        aws.Config
	}
	mock.lockDoGetS3ClientWithConfig.RLock()
	calls = mock.calls.DoGetS3ClientWithConfig
	mock.lockDoGetS3ClientWithConfig.RUnlock()
	return calls
}
