// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-static-file-publisher/service"
	"sync"
)

var (
	lockVaultClientMockChecker sync.RWMutex
)

// Ensure, that VaultClientMock does implement service.VaultClient.
// If this is not the case, regenerate this file with moq.
var _ service.VaultClient = &VaultClientMock{}

// VaultClientMock is a mock implementation of service.VaultClient.
//
//     func TestSomethingThatUsesVaultClient(t *testing.T) {
//
//         // make and configure a mocked service.VaultClient
//         mockedVaultClient := &VaultClientMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//         }
//
//         // use mockedVaultClient in code that requires service.VaultClient
//         // and then make assertions.
//
//     }
type VaultClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
	}
}

// Checker calls CheckerFunc.
func (mock *VaultClientMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("VaultClientMock.CheckerFunc: method is nil but VaultClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockVaultClientMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockVaultClientMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedVaultClient.CheckerCalls())
func (mock *VaultClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockVaultClientMockChecker.RLock()
	calls = mock.calls.Checker
	lockVaultClientMockChecker.RUnlock()
	return calls
}
